swagger: '2.0'
info:
  description: Demo ABN lookup
  version: 0.0.1
  title: APiGatewayDemo.com
schemes:
  - https
produces:
  - application/json
  - application/xml
  - multipart/form-data
  - application/x-www-form-urlencoded
consumes:
  - application/json
  - application/xml
  - multipart/form-data
  - text/html

paths:
  /lookup:
    get:
      tags:
        - User
      summary: Get a full list of users
      description: |
        Some description of the operation.
        <br />***You can use keep using `markdown` here to write out your description in more detail.***
      operationId: getAllUsers
      parameters:
        - name: abn
          in: query
          description: Input ABN number
          type: number
      produces:
        - application/json
      responses:
        '200':
          description: |
            OK. <br /> The request was successfully processed.
          schema:
            $ref: '#/definitions/AbnLookUpResponse'
        '400':
          $ref: '#/responses/400_error_response'
        '401':
          $ref: '#/responses/401_error_response'
        '403':
          $ref: '#/responses/403_error_response'
        '404':
          $ref: '#/responses/404_error_response'
        '405':
          $ref: '#/responses/405_error_response'
        '415':
          $ref: '#/responses/415_error_response'
        '500':
          $ref: '#/responses/500_error_response'
definitions:
  AbnLookUpResponse:
    description: The standard list response that should be used
    properties:
      Entity Name:
        description: name of the entity
        type: string
      ABN status:
        description: ABN status
        type: string
      Entity type:
        description: entity type
        type: string
      Goods & Services Tax(GST):
        description: GST registration
        type: string
      Main business location:
        description: business location
        type: string


responses:
  200_error_response:
    description: OK.
    examples:
      application/json: |
        {
          "status": "200",
          "description": "The request was successfully processed.",
          "more_info": ""
        }    
  201_error_response:
    description: Created.
    examples:
      application/json: |
        {
          "status": "201",
          "description": "The resource was created. The Response Location HTTP header should be returned to indicate where the newly created resource is accessible.",
          "more_info": ""
        } 
  202_error_response:
    description: Accepted.
    examples:
      application/json: |
        {
          "status": "202",
          "description": "Used for asynchronous processing - The server has accepted the request but the result is not available yet. The Response Location HTTP header may be returned to indicate where the created resource will be accessible.",
          "more_info": ""
        } 
  204_error_response:
    description: No content.
    examples:
      application/json: |
        {
          "status": "204",
          "description": "The server successfully processed the request and is not returning any content. ",
          "more_info": ""
        } 
  400_error_response:
    description: Bad Request.
    examples:
      application/json: |
        {
          "status": "400",
          "description": "The server cannot process the request.'The specified resource was not found.",
          "more_info": ""
        } 
  401_error_response:
    description: Unauthorised.
    examples:
      application/json: |
        {
          "status": "401",
          "description": "The request could not be authenticated.",
          "more_info": ""
        }
  403_error_response:
    description: Forbidden.
    examples:
      application/json: |
        {
          "status": "403",
          "description": "The request was authenticated but is not authorised to access the resource.",
          "more_info": ""
        }
  404_error_response:
    description: Not found.
    examples:
      application/json: |
        {
          "status": "404",
          "description": "The resource was not found.",
          "more_info": ""
        }
  405_error_response:
    description: Not Allowed.
    examples:
      application/json: |
        {
          "status": "405",
          "description": "The method is not implemented for this resource. The response may include an Allow header containing a list of valid methods for the resource.",
          "more_info": ""
        }
         
  408_error_response:
    description: Request Timeout.
    examples:
      application/json: |
        {
          "status": "408",
          "description": "The request timed out before a response was received.",
          "more_info": ""
        }
  415_error_response:
    description: Unsupported Media Type.
    examples:
      application/json: |
        {
          "status": "415",
          "description": "This status code indicates that the server refuses to accept the request because the content type specified in the request is not supported by the server.",
          "more_info": ""
        }
  422_error_response:
    description: Unprocessable Entity.
    examples:
      application/json: |
        {
          "status": "422",
          "description": "This status code indicates that the server received the request but it did not fulfil the requirements of the back end. An example is a mandatory field was not provided in the payload.",
          "more_info": ""
        }
  500_error_response:
    description: Internal Server Error.
    examples:
      application/json: |
        {
          "status": "500",
          "description": "An internal server error. The response body may contain error messages.",
          "more_info": ""
        }
         
  501_error_response:
    description: Method Not Implemented.
    examples:
      application/json: |-
        {
          "status": "501",
          "description": "It indicates that the request method is not supported by the server and cannot be handled for any resourceFor example, the server supports GET, POST, PUT, DELETE, and PATCH but not OPTIONS methods.",
          "more_info": ""
        }
