openapi: 3.0.3
info:
  title: Address Lookup v1
  description: Address lookup demo
  termsOfService: http://swagger.io/terms/
  contact:
    email: mohit.f.aggarwal@accenture.com
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: lookup
    description: Address lookup
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /v1/address:
    get:
      tags:
        - lookup
      summary: Address Lookup
      description: Multiple status values can be provided with comma separated strings
      operationId: AddressLookupv1
      parameters:
        - name: x-api-key
          in: header
          description: api key for authorization
          required: true
          schema:
            type: string
        - name: x-user-id
          in: header
          description: user id
          required: true
          schema:
            type: string
        - name: number
          in: query
          description: abn or acn value to be queried
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/Address'
        '400':
          description: Bad request
        '401':
          description: Unauthorised
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Not Allowed
        '408':
          description: Request Timeout
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
        '501':
          description: Method Not Implemented
          
components:
  schemas:

    Address:
      type: object
      properties:
        streetNumber:
          type: string
        suburb:
          type: string
        country:
          type: string
        pincode:
          type: string
        adressType:
          type: string
