apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-a
  description: "Service A providing an API"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-a
  providesApis:
    - service-a-api  # Defines the API it provides
