openapi: 3.0.3
info:
  title: ABN or ACN Lookup
  description:  ABN or ACN Lookup Demo
  termsOfService: http://swagger.io/terms/
  contact:
    email: mohit.f.aggarwal@accenture.com
  version: 0.0.2
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://t7snohiumi.execute-api.ap-southeast-2.amazonaws.com/develop
tags:
  - name: lookup
    description:  ABN or ACN Lookup
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /v2/lookup:
    get:
      tags:
        - lookup
      summary:  ABN or ACN Lookup
      description: Multiple status values can be provided with comma separated strings
      operationId: abnLookupv2
      parameters:
        - name: number
          in: query
          description: abn or acn value to be queried
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/AbnLookUpResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorised
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Not Allowed
        '408':
          description: Request Timeout
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
        '501':
          description: Method Not Implemented
components:
  schemas:

    AbnLookUpResponse:
      type: object
      properties:
        EntityName:
          type: string
        ABN:
          type: number
        ACN:
          type: number
        ABNStatus:
          type: string
        EntityType:
          type: string
        GST:
          type: string
        MainBusinessLocation:
          type: string
