openapi: 3.0.3
info:
  title: ABN Lookup
  description: ABN lookup demo
  termsOfService: http://swagger.io/terms/
  contact:
    email: mohit.f.aggarwal@accenture.com
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://t7snohiumi.execute-api.ap-southeast-2.amazonaws.com/develop
tags:
  - name: lookup
    description: ABN lookup
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /lookup:
    get:
      tags:
        - lookup
      summary: ABN Lookup
      description: Multiple status values can be provided with comma separated strings
      operationId: abnLookup
      parameters:
        - name: abn
          in: query
          description: abn value to be queried
          required: true
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: 
                  $ref: '#/components/schemas/AbnLookUpResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorised
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Not Allowed
        '408':
          description: Request Timeout
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
        '501':
          description: Method Not Implemented

      security:
        - petstore_auth:
            - write:pets
            - read:pets
 
components:
  schemas:

    
    AbnLookUpResponse:
      type: object
      properties:
        EntityName:
          type: string
        ABNStatus:
          type: string
        EntityType:
          type: string
        GST:
          type: string
        MainBusinessLocation:
          type: string
      xml:
        name: category
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Dogs
      xml:
        name: category

    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      xml:
        name: tag
    Pet:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: doggie
        category:
          $ref: '#/components/schemas/Category'
        photoUrls:
          type: array
          xml:
            wrapped: true
          items:
            type: string
            xml:
              name: photoUrl
        tags:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Tag'
        status:
          type: string
          description: pet status in the store
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'

  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
