apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore3
  description: Swagger PetStore Sample REST API
  links:
    - url: https://dashboard.example.com
      title: My Dashboard
      icon: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: https://github.com/mohit-aggarwal-au/AsicDemo/blob/main/WorkingPet.yaml
