apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-a-api
  description: "API provided by Service A"
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition: |
    openapi: 3.0.0
    info:
      title: Service A API
      version: 1.0.0
