apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore
  description: Swagger PetStore Sample REST API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  definition:
    $text: https://github.com/mohit-aggarwal-au/AsicDemo/blob/main/PetStore.yaml
