apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: abn_acn_lookup_demo_v2
  tags:
    - lookup
    - microservices
  links:
    - url: https://google.com
      title: Monitoring Dashboard
      icon: dashboard
    - url: https://docs.example.com/payment-service
      title: API Documentation
      icon: docs
    - url: https://logging.example.com/payment-service
      title: Logs Viewer
      icon: logs
  annotations:
    backstage.io/techdocs-ref: url:https://ap-southeast-2.console.aws.amazon.com/apigateway/main/apis/x0l6okhq8j/documentation?api=x0l6okhq8j&experience=rest-import&region=ap-southeast-2
    github.com/project-slug: url:https://github.com/mohit-aggarwal-au/AsicDemo/blob/main/LookupV2.yaml
    monitoring-url: url:https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#dashboards/dashboard/lookup-v2-dashboard?start=PT12H&end=null&autoRefresh=10
    pagerduty.com/service-url: url:https://pagerduty.com/services/ABC123
  description: Swagger ABN lookup Sample REST API
spec:
  type: openapi
  lifecycle: production
  owner: user:guest
  providesApis:
    - abn_acn_lookup_demo_v2
  consumesApis:
    - user-profile-api
  definition:
    $text: https://github.com/mohit-aggarwal-au/AsicDemo/blob/main/LookupV2.yaml
